# API Conta banco
Essa API é um exemplo de interação com contas bancárias.

# Contas
Operações relacionadas a conta bancária.

## Contas [/contas/{id_conta}]

Operação saldo, saque e depósito.

+ Parameters
    + id_conta: `1` (required, string) - O id da conta.

### Saldo [GET]

+ Response 200 (application/json)

        {
            "id": "1",
            "saldo": "1000"
        }

+ Response 404 (application/json)

        {
            "status": "FAIL",
            "mensagem": "Conta inexistente."
        }


### Saque [PUT]

+ Request (application/json)

    + Body

            {
                "valor": 250.50
            }

+ Response 200 (application/json)

        {
            "id": "1",
            "saldo": "749.5"
        }

+ Response 404 (application/json)

        {
            "status": "FAIL",
            "valor_sacado": "0",
            "mensagem": "Conta inexistente."
        }

+ Response 406 (application/json)

        {
            "status": "FAIL",
            "valor_sacado": "0",
            "mensagem": "Saldo Insuficiente."
        }

+ Response 500 (application/json)

        {
            "status": "FAIL",
            "valor_sacado": "0",
            "mensagem": "Valor deve ser um número e maior que 0."
        }


### Depósito [POST]

+ Request (application/json)

    + Body

            {
                "valor": 350
            }

+ Response 200 (application/json)

        {
            "id": "1",
            "saldo": "1099.5"
        }

+ Response 404 (application/json)

        {
            "status": "FAIL",
            "valor_depositado": "0",
            "mensagem": "Conta inexistente."
        }

+ Response 500 (application/json)

        {
            "status": "FAIL",
            "valor_depositado": "0",
            "mensagem": "Valor deve ser um número e maior que 0."
        }

## Transferência [/contas/transferencia/{id_conta_origem}/{id_conta_destino}]

Operação destinada a realizar uma transferência entre duas contas.

+ Parameters
    + id_conta_origem: `1` (required, string) - O id da conta origem.
    + id_conta_destino: `2` (required, string) - O id da conta destino.

### Transferência entre duas contas [POST]

+ Request (application/json)

    + Body

            {
                "valor": 150
            }

+ Response 200 (application/json)

        {
            "status": "OK",
            "valor_transferido": "150"
        }

+ Response 404 (application/json)

        {
            "status": "FAIL",
            "valor_transferido": "0",
            "mensagem": "Conta inexistente."
        }

+ Response 406 (application/json)

        {
            "status": "FAIL",
            "valor_transferido": "0",
            "mensagem": "Saldo Insuficiente."
        }

+ Response 500 (application/json)

        {
            "status": "FAIL",
            "valor_transferido": "0",
            "mensagem": "Valor deve ser um número e maior que 0."
        }